# Tasca M3 T01
### Descripció

**En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris.**

**Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”.**

## - Exercici 1
**Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.**

In [108]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data =iris.data
target = iris.target
features = iris.feature_names
tnames = iris.target_names

#Visualitzar 10 primers registres de data i target:
print('Les primeres 10 dades de data són:')
print(data[:10])
print()
print('Les primeres 10 dades de target són:', target[:10])


Les primeres 10 dades de data són:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Les primeres 10 dades de target són: [0 0 0 0 0 0 0 0 0 0]


## - Exercici 2
**Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.**

In [107]:
#no podem utilitzar np.concatenate perque son matrius de diferent dimensió:
print('La dimensió de data és:', data.ndim )
print('La dimensió de target és:', target.ndim)
print()
array = np.column_stack((data, target))
print("Els 5 primers registres són:")
print(array[:5])



La dimensió de data és: 2
La dimensió de target és: 1

Els 5 primers registres són:
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


## - Exercici 3
**Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.**

In [106]:
mitjana_sepal = np.mean(array[:,0])
desviacio_sepal = np.std(array[:,0])
mitjana_petal = np.mean(array[:,2])
desviacio_petal = np.std(array[:,2])
print(f'La mitjana de la longitud del sèpal és {desviacio_sepal:.2f}')
print(f'La desviació estàndard de la longitud del sèpal és {desviacio_sepal:.2f}')
print()
print(f'La mitjana de la longitud del sèpal és {desviacio_petal:.2f}')
print(f'La desviació estàndard de la longitud del sèpal és {desviacio_petal:.2f}')





La mitjana de la longitud del sèpal és 0.83
La desviació estàndard de la longitud del sèpal és 0.83

La mitjana de la longitud del sèpal és 1.76
La desviació estàndard de la longitud del sèpal és 1.76


#### - Exercici 4
**Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.**

In [7]:
#com que es de dues dimensions no puc utilitzar --> np.random.choice(array, size=20, replace=False) 
#barrejo les files de la matriu i selecciono les 5 primeres:

np.random.shuffle(array)
mostra_random = array[:20]
print(mostra_random)



[[7.  3.2 4.7 1.4 1. ]
 [6.1 2.6 5.6 1.4 2. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 2.3 4.  1.3 1. ]
 [4.6 3.6 1.  0.2 0. ]
 [6.8 3.  5.5 2.1 2. ]
 [5.6 2.8 4.9 2.  2. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [7.2 3.  5.8 1.6 2. ]
 [5.6 2.5 3.9 1.1 1. ]
 [6.5 3.  5.5 1.8 2. ]
 [4.8 3.  1.4 0.1 0. ]
 [6.7 3.1 4.7 1.5 1. ]
 [5.5 3.5 1.3 0.2 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [6.3 2.8 5.1 1.5 2. ]
 [5.6 3.  4.5 1.5 1. ]]


## - Exercici 5
**Crea una matriu que mostri:**

- **La mitjana de cada característica per espècie.**

- **La desviació estàndard de cada característica per espècie.**

In [8]:
nom_especies= iris.target_names
#creo un diccionari per guardar els resultats
resultats = {}
for i, especie in enumerate(nom_especies):
    dades_sp = array[array[:,-1] == i][:, :-1]
#calculs:
    mitjana = np.mean(dades_sp, axis=0)
    std = np.std(dades_sp, axis=0)

#poso els resultats al diccionari:
    resultats[especie] = {'Mitjana': mitjana, 'Desviació_Estàndard': std}

#mostro els resultats
for especie, valors in resultats.items():
    print(f"Els resultats per l'especie {especie} son:")
    for i, feature in enumerate(features):
        print(f"-{feature}:")
        print(f"  - Mitjana: {valors['Mitjana'][i]:.2f}")
        print(f"  - Desviació_Estàndar: {valors['Desviació_Estàndard'][i]:.2f}")
    print()

Els resultats per l'especie setosa son:
-sepal length (cm):
  - Mitjana: 5.01
  - Desviació_Estàndar: 0.35
-sepal width (cm):
  - Mitjana: 3.43
  - Desviació_Estàndar: 0.38
-petal length (cm):
  - Mitjana: 1.46
  - Desviació_Estàndar: 0.17
-petal width (cm):
  - Mitjana: 0.25
  - Desviació_Estàndar: 0.10

Els resultats per l'especie versicolor son:
-sepal length (cm):
  - Mitjana: 5.94
  - Desviació_Estàndar: 0.51
-sepal width (cm):
  - Mitjana: 2.77
  - Desviació_Estàndar: 0.31
-petal length (cm):
  - Mitjana: 4.26
  - Desviació_Estàndar: 0.47
-petal width (cm):
  - Mitjana: 1.33
  - Desviació_Estàndar: 0.20

Els resultats per l'especie virginica son:
-sepal length (cm):
  - Mitjana: 6.59
  - Desviació_Estàndar: 0.63
-sepal width (cm):
  - Mitjana: 2.97
  - Desviació_Estàndar: 0.32
-petal length (cm):
  - Mitjana: 5.55
  - Desviació_Estàndar: 0.55
-petal width (cm):
  - Mitjana: 2.03
  - Desviació_Estàndar: 0.27



## - Exercici 6
- **Calcula la quantitat de mostres per espècie.**

In [34]:
quantitat_mostres_spp = np.bincount(target)
for i, quantitat in enumerate(quantitat_mostres_spp):
    print(f"El nombre de mostres per l'espècie {tnames[i]} és: {quantitat}")

El nombre de mostres per l'espècie setosa és: 50
El nombre de mostres per l'espècie versicolor és: 50
El nombre de mostres per l'espècie virginica és: 50


- **Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"**

In [36]:
#AQUEST CODI M'AJUDA A VISUALITZAR COM ESTA ESTRUCTURADA LA DATA
for especie, valors in resultats.items():
   print(especie)
   print(features)
   print(valors)


setosa
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
{'Mitjana': array([5.006, 3.428, 1.462, 0.246]), 'Desviació_Estàndard': array([0.34894699, 0.37525458, 0.17191859, 0.10432641])}
versicolor
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
{'Mitjana': array([5.936, 2.77 , 4.26 , 1.326]), 'Desviació_Estàndard': array([0.51098337, 0.31064449, 0.46518813, 0.19576517])}
virginica
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
{'Mitjana': array([6.588, 2.974, 5.552, 2.026]), 'Desviació_Estàndard': array([0.62948868, 0.31925538, 0.54634787, 0.27188968])}


In [105]:
# Per assegurar-nos de que qualsevol valor de mitjana de la sepal length sigui major al principi de la iteració, el valor és -1.
max_mitjana_sepal_length = -1  
#Aixo s'utilitza per emmagatzemar el nom de la especie que tingui la mitja més alta:
especie_max_mitjana_sepal_length = ""

for especie, valors in resultats.items():
    #valors['Mitjana'][0] perque volem de la llista 'Mitjana' el primer valor que correspon a la sepal_length
    mitjana_sepal_length = valors['Mitjana'][0]
    print(f"Per l'espècie {especie} i la variable {features[0]}:")
    print(f"  - Mitjana: {mitjana_sepal_length:.2f} cm")
    
    if mitjana_sepal_length > max_mitjana_sepal_length:
        #max_mitjana_sepal_lenght guardara la mitjana més alta de la loop
        max_mitjana_sepal_length = mitjana_sepal_length
        #aqui actualitzem el especie_max_mitjana_sepal_length amb el nom de l'especie amb la mitjana més alta que ha complert la condició anterior
        especie_max_mitjana_sepal_length = especie

print(f"\nL'espècie amb el valor màxim de mitjana de la variable {features[0]} és l'espècie: {especie_max_mitjana_sepal_length}")


Per l'espècie setosa i la variable sepal length (cm):
  - Mitjana: 5.01 cm
Per l'espècie versicolor i la variable sepal length (cm):
  - Mitjana: 5.94 cm
Per l'espècie virginica i la variable sepal length (cm):
  - Mitjana: 6.59 cm

L'espècie amb el valor màxim de mitjana de la variable sepal length (cm) és l'espècie: virginica


## - Exercici 7
- **Calcula la matriu de correlació entre les variables.**

In [50]:
matriu_correlacio = np.corrcoef(data, rowvar=False)
#rowvar=False es per indicar que cada columna representa una variable i cada fila és una observació .
print(matriu_correlacio)

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


- **Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho.**

In [102]:
#calculo la mitjana: selecionant per totes les files, el valor que hi ha a la tercera columan que correspon a la longitud dels pètals
mitjana_petal_length = np.mean(data[:,2])
print(f"La mitjana de la longitud del petal és {mitjana_petal_length:.1f}")
print()
#aqui creo una array en la qual els elements que siguin True compliran la condició proposada i si són False no. Aleshores agafem de la array 'data' només els valors que compleixin la condició true i es pasa a dir valors majors
valors_majors = data[data[:, 2] > mitjana_petal_length]

print(f'Els valors majors a la mitjana de la longitud dels petals són:')
print(valors_majors)

La mitjana de la longitud del petal és 3.8

Els valors majors a la mitjana de la longitud dels petals són:
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]


- **Troba la mostra amb els pètals més grans.**

In [82]:
#he de trobar l'especie que tingui l'area de pètal més gran es a dir 'petal length (cm)' x 'petal width (cm)'
area_petal = data[:,2]*data[:,3]
#per obtenir l'index de la mostra utilitzo np.argmax en ves de max() que em donaria el valor maxim d'area pero no l'index.
index_max_petal = np.argmax(area_petal)
mostra_max_petal = data[index_max_petal]
print(f"La mostra que té l'àrea de petal més gran és:", (mostra_max_petal))


La mostra que té l'àrea de petal més gran és: [7.7 2.6 6.9 2.3]


## - Exercici 8
- **Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.**

In [100]:
#primer calculo la longitud mitjana dels sèpals i pètals
mitjana_sepal = np.mean(data[:, 0])  
mitjana_petal = np.mean(data[:, 2]) 
#calculo la diferencia entre els dos valors:
diferencia = mitjana_sepal - mitjana_petal
#amb la funcio np.argmax busco l'index que tingui la diferencia més gran, igual com he fet a l'exercici 7 pero de forma mes reduida:
especie_max_dif = tnames[np.argmax(diferencia)]

#per veure la mostra
mostra_max_dif = data[np.argmax(diferencia)]

print(f"La {especie_max_dif} és l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals")
print(f"La mostra és la següent: {mostra_max_dif} ")


La setosa és l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals
La mostra és la següent: [5.1 3.5 1.4 0.2] 
